/* EXECUTED EVERYTIME THE OPTION IS CALLED */
/* PRIORITY 28 */
/* EXECUTED ONLY WHEN THE OPTION IS INSTALLED */
@FMT(CMP,@WIZGET(INSTALL_STEP)<3,'®FMT(CHR,26)');
@WIZRESET;
@EXEC(SQL=REFRESH_MENU);
 