/*
 * File: app/view/Buy/Itm/QuickResult.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Buy.Itm.QuickResult', {
    extend: 'Ext.form.Panel',
    alias: 'widget.buyitmquickresult',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.field.Search',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        smsToolbar: 'Result',
        smsResultUrl: 'cgi=mFloor_xml_grid.xml&ExtGridUsp=mFloor_buy_itm_search',
        smsHost: 'buyhost',
        smsAction: 'runquery',
        smsToolbarKeep: 'buyrecstart;buyordstart;buydsdstart',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Quick search',
                layout: {
                    type: 'hbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        cls: 'sms-title-close-btn',
                        itemId: 'closeBtn'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                cls: 'sms-child-tool',
                docked: 'top',
                ui: 'light',
                layout: {
                    type: 'hbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        flex: 1,
                        name: 'FindVendor',
                        placeHolder: 'Type in item name or code'
                    }
                ]
            },
            {
                xtype: 'label',
                cls: 'sms-result-info',
                docked: 'top',
                html: 'or select an item'
            },
            {
                xtype: 'list',
                cls: 'sms-result-grid',
                itemId: 'resultGrid',
                emptyText: 'No record found',
                itemTpl: [
                    '<table class="sms-itm-result-table">',
                    '    <tr>',
                    '        <td class="sms-itm-result-icon"></td>',
                    '        <td>',
                    '            <table><tr><td class="sms-itm-result-desc" colspan="2">{F02}</td></tr></table>',
                    '            <table>',
                    '                <tr>',
                    '                    <td class="sms-itm-result-title">Code</td>',
                    '                    <td class="sms-itm-result-title">Vnd code</td>',
                    '                    <td class="sms-itm-result-title">Net cost</td>',
                    '                </tr>',
                    '                <tr>',
                    '                    <td class="sms-itm-result-data">{F01}</td>',
                    '                    <td class="sms-itm-result-data">{F26}</td>',
                    '                    <td class="sms-itm-result-data">{F196S}</td>',
                    '                </tr>',
                    '            </table>',
                    '        </td>',
                    '        <td class="sms-itm-result-arrow"></td>',
                    '    </tr>',
                    '</table>'
                ]
            }
        ]
    }

});