/*
 * File: app/view/Buy/Rec/DocOpen.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Buy.Rec.DocOpen', {
    extend: 'Ext.form.Panel',
    alias: 'widget.buyrecdocopen',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.field.Search',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        smsHost: 'buyhost',
        smsToolbar: 'Open',
        smsToolbarKeep: 'buystart',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Open receiving',
                items: [
                    {
                        xtype: 'button',
                        cls: 'sms-title-close-btn',
                        itemId: 'closeBtn'
                    },
                    {
                        xtype: 'button',
                        smsExec: 'jsFct=BuyCtrl.recDocNew',
                        align: 'right',
                        cls: 'sms-title-add-btn'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                cls: 'sms-child-tool',
                docked: 'top',
                layout: {
                    type: 'hbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        flex: 1,
                        width: 290,
                        name: 'FindVendor',
                        placeHolder: '\'Filter by Vnd Id, Po# or Trs#'
                    }
                ]
            },
            {
                xtype: 'label',
                cls: 'sms-result-info',
                docked: 'top',
                itemId: 'resultHdrText'
            },
            {
                xtype: 'list',
                cls: 'sms-result-grid',
                itemId: 'resultGrid',
                itemTpl: [
                    '<table class="sms-doc-result-table">',
                    '	<tr>',
                    '        <td>',
                    '            <table><tr><td class="sms-doc-result-desc">{F334}</td></tr></table>',
                    '            <table>',
                    '            <tr>',
                    '                <td class="sms-doc-result-title">VendorId</td>',
                    '                <td class="sms-doc-result-title">PO#</td>',
                    '                <td class="sms-doc-result-title">Type</td>',
                    '                <td class="sms-doc-result-title">Trans#</td>',
                    '                <td class="sms-doc-result-title">Date</td>',
                    '            </tr>',
                    '            <tr>',
                    '                <td class="sms-doc-result-data">{F27}</td>',
                    '                <td class="sms-doc-result-data">{F91}</td>',
                    '                <td class="sms-doc-result-data">{F1068}</td>',
                    '                <td class="sms-doc-result-data">{F1032}</td>',
                    '                <td class="sms-doc-result-data">{F76S}</td>',
                    '            </tr>',
                    '            </table>',
                    '        </td>',
                    '        <td class="sms-doc-result-arrow"></td>',
                    '	</tr>',
                    '</table>'
                ]
            }
        ]
    }

});