/*
 * File: app/view/Buy/Rec/ItmStart.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Buy.Rec.ItmStart', {
    extend: 'Ext.form.Panel',
    alias: 'widget.buyrecitmstart',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.field.Search',
        'Ext.form.FieldSet',
        'Ext.Label',
        'Ext.field.Number'
    ],

    config: {
        smsToolbar: 'Item',
        smsHost: 'buyhost',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        cls: 'sms-title-close-btn',
                        itemId: 'closeBtn'
                    },
                    {
                        xtype: 'button',
                        smsExec: 'FCT=3650',
                        align: 'right',
                        cls: 'sms-title-delete-btn'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                cls: 'sms-child-tool',
                docked: 'top',
                layout: {
                    type: 'hbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        flex: 1,
                        itemId: 'searchEdit',
                        placeHolder: 'Enter item code'
                    }
                ]
            },
            {
                xtype: 'container',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'container',
                                height: 30,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'sms-displayfield',
                                        width: 55,
                                        label: '#',
                                        name: 'F1101',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        cls: 'sms-displayfield',
                                        width: 150,
                                        clearIcon: false,
                                        name: 'F01',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'label',
                                        flex: 1,
                                        cls: 'sms-label-title',
                                        html: 'Count'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        cls: 'sms-message-text',
                        itemId: 'messageText'
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Vendor code',
                                labelAlign: 'top',
                                name: 'REC_REG-F26',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                label: 'Item description',
                                labelAlign: 'top',
                                name: 'REC_REG-F1041',
                                readOnly: true
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'numberfield',
                                width: 70,
                                clearIcon: false,
                                label: 'Format',
                                labelAlign: 'top',
                                name: 'REC_REG-F19',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                width: 90,
                                label: 'Fmts',
                                labelAlign: 'top',
                                value: 'Case',
                                readOnly: true
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'currencyfield',
                                        width: 90,
                                        clearIcon: false,
                                        label: 'Base cost',
                                        labelAlign: 'top',
                                        name: 'REC_REG-F38',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'currencyfield',
                                        width: 91,
                                        label: 'Net cost',
                                        labelAlign: 'top',
                                        name: 'F151',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        width: 90,
                                        label: 'Total count',
                                        labelAlign: 'top',
                                        name: 'TOTAL_COUNT',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        width: 90,
                                        label: 'Format',
                                        labelAlign: 'top',
                                        value: 'Case',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        smsExec: 'FCT=3010&ATER=1&ENTRY=',
                                        width: 79,
                                        clearIcon: false,
                                        label: 'Case',
                                        labelAlign: 'top',
                                        name: 'REC_REG-F1003'
                                    },
                                    {
                                        xtype: 'currencyfield',
                                        smsExec: 'FCT=3630&SKIPFOCUS=1&ENTRY=',
                                        width: 105,
                                        clearIcon: false,
                                        label: 'Total cost',
                                        labelAlign: 'top',
                                        name: 'REC_REG-F65'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});