/*
 * File: app/view/Buy/Rec/LinQuickResult.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Buy.Rec.LinQuickResult', {
    extend: 'Ext.form.Panel',
    alias: 'widget.buyreclinquickresult',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        smsToolbar: 'Line',
        smsHost: 'buyhost',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'List line items',
                layout: {
                    type: 'hbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        cls: 'sms-title-close-btn',
                        itemId: 'closeBtn'
                    }
                ]
            },
            {
                xtype: 'label',
                cls: 'sms-result-info',
                docked: 'top',
                html: 'Select an item from the list',
                itemId: 'resultHdrText'
            },
            {
                xtype: 'list',
                cls: 'sms-result-grid',
                itemId: 'resultGrid',
                emptyText: 'No record found',
                itemTpl: [
                    '<table class="sms-itm-result-table">',
                    '    <tr>',
                    '        <td class="sms-itm-result-icon"></td>',
                    '        <td>',
                    '            <table><tr><td class="sms-itm-result-desc" colspan="2">{F1041}</td></tr></table>',
                    '            <table>',
                    '                <tr>',
                    '                    <td class="sms-itm-result-title">Code</td>',
                    '                    <td class="sms-itm-result-title">Case</td>',
                    '                    <td class="sms-itm-result-title">Total</td>',
                    '                </tr>',
                    '                <tr>',
                    '                    <td class="sms-itm-result-data">{CODE}</td>',
                    '                    <td class="sms-itm-result-data">{F1003}</td>',
                    '                    <td class="sms-itm-result-data">{AMOUNT}</td>',
                    '                </tr>',
                    '            </table>',
                    '        </td>',
                    '        <td class="sms-itm-result-arrow"></td>',
                    '    </tr>',
                    '</table>'
                ]
            }
        ]
    }

});