/*
 * File: app/view/Buy/Rec/Start.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Buy.Rec.Start', {
    extend: 'Ext.form.Panel',
    alias: 'widget.buyrecstart',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.field.Search',
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date'
    ],

    config: {
        smsToolbar: 'Recv',
        smsHost: 'buyhost',
        smsToolbarKeep: 'none',
        smsTaskbar: 'Buying',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        cls: 'sms-title-back-btn',
                        itemId: 'suspendDocBtn'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                cls: 'sms-child-tool',
                docked: 'top',
                ui: 'light',
                layout: {
                    type: 'hbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        flex: 1,
                        itemId: 'searchEdit',
                        placeHolder: 'Enter item code'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Receiving',
                items: [
                    {
                        xtype: 'container',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'textfield',
                                width: 80,
                                label: 'Vendor Id',
                                labelAlign: 'top',
                                name: 'F27',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                width: 220,
                                label: 'Vendor name',
                                labelAlign: 'top',
                                name: 'F334',
                                readOnly: true
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'textfield',
                                width: 70,
                                label: 'Trs #',
                                labelAlign: 'top',
                                name: 'F1032',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                width: 110,
                                label: 'Ord #',
                                labelAlign: 'top',
                                name: 'F91',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                width: 120,
                                label: 'Reference #',
                                labelAlign: 'top',
                                name: 'F1245',
                                readOnly: true
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'datepickerfield',
                                width: 135,
                                label: 'Delivery',
                                labelAlign: 'top',
                                name: 'F1246',
                                readOnly: true
                            },
                            {
                                xtype: 'datepickerfield',
                                width: 135,
                                label: 'Invoice',
                                labelAlign: 'top',
                                name: 'F254',
                                readOnly: true
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                padding: '10 0 10 0',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        margin: '0 0 5 0',
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'button',
                                smsExec: 'jsFct=BuyCtrl.itmQuickResult',
                                cls: 'sms-start-btn-green',
                                margin: 5,
                                icon: 'resources/images/BuyMenuQuick.png',
                                iconAlign: 'right',
                                text: 'Quick<br/>search'
                            },
                            {
                                xtype: 'button',
                                cls: 'sms-start-btn-green',
                                itemId: 'listItmBtn',
                                margin: 5,
                                icon: 'resources/images/InvStartList.png',
                                iconAlign: 'right',
                                text: 'List<br/>line<br/>items'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        margin: '0 0 5 0',
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'button',
                                cls: 'sms-start-btn-green',
                                itemId: 'currentItmBtn',
                                margin: 5,
                                icon: 'resources/images/BuyMenuCurrent.png',
                                iconAlign: 'right',
                                text: 'Show<br/>current<br/>line'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});