/*
 * File: app/view/Itm/Info.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Itm.Info', {
    extend: 'Ext.form.Panel',
    alias: 'widget.itminfo',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.field.Search',
        'Ext.form.FieldSet',
        'Ext.Label',
        'Ext.field.Number'
    ],

    config: {
        smsToolbar: 'Info',
        smsHost: 'itmhost',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        cls: 'sms-title-close-btn',
                        itemId: 'closeBtn'
                    },
                    {
                        xtype: 'button',
                        cls: 'sms-title-tasks-btn',
                        itemId: 'tasksBtn'
                    },
                    {
                        xtype: 'button',
                        smsExec: 'jsFct=TasksCtrl.labelPrintView',
                        align: 'right',
                        cls: 'sms-title-print-act-btn',
                        hidden: false,
                        itemId: 'printActBtn'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                cls: 'sms-child-tool',
                docked: 'top',
                layout: {
                    type: 'hbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        flex: 1,
                        itemId: 'searchEdit',
                        placeHolder: 'Enter item code'
                    }
                ]
            },
            {
                xtype: 'container',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'container',
                                height: 30,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'sms-displayfield',
                                        width: 150,
                                        clearIcon: false,
                                        name: 'F01',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'label',
                                        flex: 1,
                                        cls: 'sms-label-title',
                                        html: 'Item Information'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        width: 300,
                                        clearIcon: false,
                                        label: 'POS description',
                                        labelAlign: 'top',
                                        name: 'F02',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                hidden: true,
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'currencyfield',
                                                        cls: 'sms-priceamt',
                                                        width: 150,
                                                        label: 'Active price',
                                                        labelAlign: 'top',
                                                        name: 'F1007',
                                                        readOnly: true
                                                    },
                                                    {
                                                        xtype: 'numberfield',
                                                        cls: 'sms-priceqty',
                                                        width: 100,
                                                        label: 'Qty',
                                                        labelAlign: 'top',
                                                        name: 'F1006',
                                                        readOnly: true
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'currencyfield',
                                        cls: 'sms-priceamt',
                                        width: 170,
                                        label: 'Regular',
                                        labelAlign: 'top',
                                        name: 'UnitPrice',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: 'sms-priceqty',
                                        width: 100,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F31s',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                hidden: true,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'currencyfield',
                                        cls: 'sms-priceamt',
                                        width: 150,
                                        label: 'Tpr price',
                                        labelAlign: 'top',
                                        name: 'F181',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: 'sms-priceqty',
                                        width: 100,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F182',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'currencyfield',
                                        cls: 'sms-priceamt',
                                        width: 170,
                                        label: 'Sale price',
                                        labelAlign: 'top',
                                        name: 'F136',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: 'sms-priceqty',
                                        width: 100,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F135S',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                hidden: true,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'currencyfield',
                                        cls: 'sms-priceamt',
                                        width: 150,
                                        label: 'Instore',
                                        labelAlign: 'top',
                                        name: 'F1133',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: 'sms-priceqty',
                                        width: 100,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F1134',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                hidden: false,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'currencyfield',
                                        cls: 'sms-priceamt',
                                        width: 170,
                                        label: 'Sale Thrive Price',
                                        labelAlign: 'top',
                                        name: 'STP',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: 'sms-priceqty',
                                        width: 100,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'STPQty',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'textfield',
                                width: 300,
                                clearIcon: false,
                                label: 'eCoupon description',
                                labelAlign: 'top',
                                name: 'F1033',
                                readOnly: true
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'currencyfield',
                                        cls: 'sms-priceamt',
                                        width: 170,
                                        label: 'Net Cost',
                                        labelAlign: 'top',
                                        name: 'F196',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: 'sms-priceqty',
                                        width: 100,
                                        label: 'Case',
                                        labelAlign: 'top',
                                        name: 'F19',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        width: 150,
                                        label: 'Shelf Id',
                                        labelAlign: 'top',
                                        name: 'F117',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: 'sms-number',
                                        width: 150,
                                        label: 'Face Position',
                                        labelAlign: 'top',
                                        name: 'F1030',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        width: 150,
                                        label: 'Tax Flags',
                                        labelAlign: 'top',
                                        name: 'F81S',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        width: 150,
                                        label: 'Restrict',
                                        labelAlign: 'top',
                                        name: 'F170',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        width: 150,
                                        label: 'Sub dept',
                                        labelAlign: 'top',
                                        name: 'F04',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        width: 150,
                                        label: 'Bottle Deposit',
                                        labelAlign: 'top',
                                        name: 'F05',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset'
                    }
                ]
            }
        ]
    }

});