IF ((SELECT OBJECT_ID('dbo.KDLOC_REPLACE_F1081')) IS NOT NULL)
	DROP FUNCTION [dbo].KDLOC_REPLACE_F1081
GO

CREATE FUNCTION dbo.KDLOC_REPLACE_F1081(@OrgFct INT, @NewFct INT)
RETURNS VARCHAR(1000)
AS
BEGIN
	DECLARE @F1081 VARCHAR(1000) 
	DECLARE @I INT
	DECLARE @ParamOrg TABLE (NAME VARCHAR(60),VALUE VARCHAR(60))
	DECLARE @ParamNew TABLE (NAME VARCHAR(60),VALUE VARCHAR(60))
	DECLARE @Prm VARCHAR(120)

	/* ORIGINAL FUNCTION */
	SET @I=1
	SELECT @F1081=REPLACE(F1081,' ',',') FROM  FCT_TAB WHERE F1063=@OrgFct

	WHILE @I<=(SELECT LEN(@F1081)-LEN(REPLACE(@F1081,',',''))+1)
	BEGIN
		SET @Prm=dbo.Sms_tools_comaparam(@F1081,@I)
		INSERT INTO @ParamOrg SELECT Name=substring(@Prm,1,CHARINDEX('=',@Prm)-1),Value=substring(@Prm,CHARINDEX('=',@Prm)+1,1000)
		SET @I=@I+1
	END

	/* NEW FUNCTION */
	SET @I=1
	SELECT @F1081=REPLACE(F1081,' ',',') FROM  FCT_TAB WHERE F1063=@NewFct

	WHILE @I<=(SELECT LEN(@F1081)-LEN(REPLACE(@F1081,',',''))+1)
	BEGIN
		SET @Prm=dbo.Sms_tools_comaparam(@F1081,@I)
		INSERT INTO @ParamNew SELECT Name=substring(@Prm,1,CHARINDEX('=',@Prm)-1),Value=substring(@Prm,CHARINDEX('=',@Prm)+1,1000)
		SET @I=@I+1
	END

	SELECT @F1081=STUFF(
		(
		SELECT 
			','+ISNULL(ORG.NAME,NEW.NAME)+'='+ISNULL(NEW.VALUE,'')
		FROM @ParamOrg ORG
		FULL OUTER JOIN @ParamNew NEW ON ORG.NAME=NEW.NAME
		FOR XML PATH('')
		),1,1,'')

	RETURN @F1081
END
