/*
 * File: app/view/Trs/Host.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Trs.Host', {
    extend: 'Ext.Panel',
    alias: 'widget.trshost',

    requires: [
        'Ext.Toolbar',
        'Ext.SegmentedButton',
        'Ext.Img'
    ],

    config: {
        smsTaskbar: 'Home',
        cls: 'sms-view-trs',
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                cls: 'sms-desktop-tool',
                docked: 'bottom',
                scrollable: 'horizontal',
                items: [
                    {
                        xtype: 'segmentedbutton',
                        itemId: 'tools',
                        allowDepress: true
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'cards',
                layout: 'card'
            },
            {
                xtype: 'container',
                docked: 'bottom',
                margin: '0 0 5 0',
                layout: {
                    type: 'hbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'image',
                        height: 65,
                        width: 185,
                        src: 'resources/images/KinneyDrugs.png'
                    }
                ]
            }
        ]
    }

});