/*
 * File: app/view/Trs/Start.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Trs.Start', {
    extend: 'Ext.form.Panel',
    alias: 'widget.trsstart',

    requires: [
        'Ext.TitleBar',
        'Ext.Button'
    ],

    config: {
        smsTaskbar: 'Home',
        smsHost: 'trshost',
        smsToolbar: 'Menu',
        smsToolbarKeep: 'none',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Main Menu',
                items: [
                    {
                        xtype: 'button',
                        cls: 'sms-title-logout-btn',
                        itemId: 'closeBtn'
                    }
                ]
            },
            {
                xtype: 'container',
                padding: '10 0 10 0',
                items: [
                    {
                        xtype: 'container',
                        margin: '0 0 5 0',
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'button',
                                smsExec: 'jsWin=itminfo',
                                cls: 'sms-start-btn-blue',
                                margin: '0 5 0 0',
                                icon: 'resources/images/ItmMenuTrs.png',
                                iconAlign: 'right',
                                text: 'Item<br>Review'
                            },
                            {
                                xtype: 'button',
                                smsExec: 'jsFct=BuyCtrl.recDocOpen',
                                cls: 'sms-start-btn-blue',
                                icon: 'resources/images/InvMenuTrs.png',
                                iconAlign: 'right',
                                text: 'Back Room<br>Stock Menu'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});