/*
 * File: app/view/Start/Login.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Start.Login', {
    extend: 'Ext.form.Panel',
    alias: 'widget.startlogin',

    requires: [
        'Ext.TitleBar',
        'Ext.Img',
        'Ext.field.Password',
        'Ext.field.Checkbox',
        'Ext.Button'
    ],

    config: {
        smsTaskbar: 'Start',
        smsHost: 'starthost',
        cls: 'sms-login-view',
        itemId: 'startLoginForm',
        padding: 0,
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: ' Welcome to mFloor'
            },
            {
                xtype: 'container',
                cls: 'sms-login-container',
                items: [
                    {
                        xtype: 'image',
                        cls: 'sms-login-logo',
                        height: 80,
                        itemId: 'startLogoImg',
                        src: 'resources/images/StartLoginLogo.png'
                    },
                    {
                        xtype: 'container',
                        cls: 'sms-login-fld-container',
                        margin: '10 0',
                        layout: {
                            type: 'vbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                width: 270,
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                cls: 'sms-login-text',
                                                itemId: 'startUserEdit',
                                                label: 'User code',
                                                labelAlign: 'top'
                                            },
                                            {
                                                xtype: 'passwordfield',
                                                cls: 'sms-login-text',
                                                itemId: 'startPasswordEdit',
                                                margin: '10 0 0 0',
                                                label: 'Password',
                                                labelAlign: 'top'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        margin: '20 0 0 0',
                                        layout: {
                                            type: 'hbox',
                                            align: 'center'
                                        },
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                flex: 1,
                                                cls: 'sms-login2-checkbox',
                                                itemId: 'startSavePasswordCheck',
                                                width: 193,
                                                label: 'Remember<br>password',
                                                labelAlign: 'right',
                                                labelWidth: 120
                                            },
                                            {
                                                xtype: 'button',
                                                cls: 'sms-login-btn',
                                                height: 50,
                                                itemId: 'startLoginBtn',
                                                margin: 5,
                                                ui: 'confirm',
                                                width: 90,
                                                iconAlign: 'right',
                                                iconCls: 'arrow_right',
                                                text: 'Login'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});