/* ADD THE KINNEY AR TABLES */
@FMT(CMP,@DBHOT(FINDTABLE,KINNEY_AR_TRS)=,'®CREATE(KINNEY_AR_TRS,TRSCLT)');
@FMT(CMP,@DBHOT(FINDTABLE,KINNEY_AR_ACC)=,'®CREATE(KINNEY_AR_ACC,RPTCLTN)');

/* ADD CREDIT LIMIT AND TAX EXEMPTION */
@dbExec(IF NOT EXISTS (SELECT SYSOBJECTS.NAME FROM SYSOBJECTS INNER JOIN SYSCOLUMNS ON SYSOBJECTS.ID = SYSCOLUMNS.ID WHERE SYSCOLUMNS.NAME='F1165' AND SYSOBJECTS.NAME='KINNEY_AR_ACC')
ALTER TABLE KINNEY_AR_ACC ADD F1165 MONEY NULL,F1160 VARCHAR(5) NULL);

/* ADD CUSTOMER CLASS (charge only, payment only...) */
@dbExec(IF NOT EXISTS (SELECT SYSOBJECTS.NAME FROM SYSOBJECTS INNER JOIN SYSCOLUMNS ON SYSOBJECTS.ID = SYSCOLUMNS.ID WHERE SYSCOLUMNS.NAME='F1153' AND SYSOBJECTS.NAME='KINNEY_AR_ACC')
ALTER TABLE KINNEY_AR_ACC ADD F1153 INT NULL);

/* ADD CUSTOMER NAME (charge only, payment only...) */
@dbExec(IF NOT EXISTS (SELECT SYSOBJECTS.NAME FROM SYSOBJECTS INNER JOIN SYSCOLUMNS ON SYSOBJECTS.ID = SYSCOLUMNS.ID WHERE SYSCOLUMNS.NAME='F1155' AND SYSOBJECTS.NAME='KINNEY_AR_ACC')
ALTER TABLE KINNEY_AR_ACC ADD F1155 VARCHAR(50) NULL);

@TOOLS(INSTALL_USP,Usp\KINNEYDRUG_FUNCTIONS.SQL);
@TOOLS(INSTALL_USP,Usp\PAY_CHARGE_USP.SQL);
@TOOLS(INSTALL_USP,Usp\KINNEYDRUG_AR_EXPORT.SQL);
