/* Import: 1.KinneyDrugs Item Load */

@WIZINIT;
@WIZEDIT(CONFIRM=NO,Do you want to drop the items file?);
@WIZDISPLAY;
@FMT(CMP,@WIZGET(CONFIRM)=YES,'®CREATE(ALT_TAB,ALT);®CREATE(OBJ_TAB,OBJ);®CREATE(POS_TAB,POS);®CREATE(PRICE_TAB,PRICE);®CREATE(COST_TAB,COST);');

@WIZRPL(KINNEYDRUG.INI[IMPORT]ITEMLOAD=1);
@DBHOT(KINNEYDRUG.INI,SET,KINNEYDRUG.INI[*);

@EXEC(SQI=KDLOC_ItemImport_all);

