/* Ad Batch Tool: Invoice list */

@WIZRPL(FORM=InvList);
@WIZRPL(TITLE=Ad Batch: Invoice list);

@WIZSET(TOP=50);
@WIZSET(LEFT=625);
@WIZSET(HEIGHT=275);
@WIZSET(WIDTH=780);

@WIZRPL(STATE=FOCUS);

@dbHot(REG,SET,USER@USER/KINNEY_INVLIST*);
@FMT(CMP,@dbHot(REG,USER@USER/KINNEY_INVLIST/INVOICE)=,'®dbHot(REGSET,USER@USER/KINNEY_INVLIST/INVOICE,,)')
@dbHot(REGSET,USER@USER/Kinney_invlist/PageNum,,"1")

@EXEC(htt=Script\SKU_BAT_KDLOC_AdBatch_InvList);
