/* Import: Milk Club points */

@WIZSET(DATE=@DSDD);
@WIZRPL(TARGET=901);
@WIZRPL(EXEC=SQL=KDLOC_MILKCLUB_PTS_IMPORT);
@EXEC(SQM=EXE_DEPLOY);

/* SEND CONFIRMATION MESSAGE */
@WIZRPL(MESSAGE=Milk club points import done);
@WIZRPL(APPLICATION=@DBHOT(APPLICATION));
@WIZRPL(COMPUTER=@DBHOT(COMPUTER));
@EXEC(SQM=KDLOC_MilkClub_done_msg);