/* Ad Batch Report: Ad Proofing Report */

@WIZINIT;
@WIZEDIT(DITTO,SELECT A DITTO NUMBER);
@WIZTARGET(TARGET=RAL,SELECT F1000,F1018 FROM STO_TAB WHERE F1180='1' ORDER BY F1000);
@WIZDISPLAY;

@WIZINIT;
@WIZFIL(BUYER,,SELECT 'ALL' AS F193 UNION ALL SELECT F193 FROM OBJ_TAB WHERE F01 IN (SELECT ALLO.F01 FROM HEADER_BAT HDR JOIN ALLOW_BAT ALLO ON ALLO.F902=HDR.F902 WHERE CHARINDEX('-',HDR.F913)>0 AND SUBSTRING(HDR.F913,1,CHARINDEX('-',HDR.F913)-1)='@WIZGET(DITTO)') AND ISNULL(F193,'')!='' GROUP BY F193);
@WIZFIL(FRM,width=700,label=SELECT A BUYER,default=1,field=F193);
@WIZDISPLAY;

@WIZRPL(DATECREATED=@DSDF);
@WIZRPL(TIMECREATED=@FMT(T6D,@NOW));

/* AR Credits from Ad Sheets */
@wizrpl(ExtGridUsp=Kinney_AdProofing_xls);
@WIZSET(FILENAME=Kinney_AdProofing.xls);
@WIZRPL(OUTPUT=@OFFICEDBT\@WIZGET(FILENAME))
@EXEC(XLS=RTM\Kinney_AdProofing.xls);
@wizClr(OUTPUT);

@WIZRPL(TITLE=SaveFile);
@WIZRPL(FORM=SaveFile);
@WIZRPL(width=1)
@WIZRPL(height=1)
@EXEC(HTT=script\SKU_BAT_KDLOC_save_xls);
