/* Export: Milk Club points */

@WIZINIT;
@WIZDATE(DATE);
@WIZDISPLAY;

@WIZRPL(TARGET=901);
@WIZRPL(EXEC=SQL=KDLOC_MILKCLUB_PTS_EXPORT,SCH_TASK=0);
@EXEC(SQM=EXE_DEPLOY);

/* SEND CONFIRMATION MESSAGE */
@WIZRPL(MESSAGE=Milk club points export done);
@WIZRPL(APPLICATION=@DBHOT(APPLICATION));
@WIZRPL(COMPUTER=@DBHOT(COMPUTER));
@EXEC(SQM=KDLOC_MilkClub_done_msg);