DELETE FROM DRIL_FILE WHERE F1597 LIKE 'PDA%';

CREATE VIEW Dril_file_load AS SELECT F1000,F1597,F1606,F1607,F1608 FROM DRIL_FILE;

INSERT INTO Dril_file_load VALUES
('PAL','PDAMENU','MAIN MENU','',),
('PAL','PDAREC','BACK ROOM STOCK MENU','',);

@UPDATE_BATCH(JOB=ADDRPL,TAR=DRIL_FILE,KEY=F1000=:F1000 and F1597=:F1597,
SRC=SELECT * FROM Dril_file_load);

DROP TABLE Dril_file_load;

@TOOLS(MAP_BACKUP,Dril_File,'Load\Dril_file_load.SQL',DRIL_FILE);
