if object_id('KDLOC_Label_ClearF2119') is not null DROP PROCEDURE KDLOC_Label_ClearF2119;
GO

CREATE PROCEDURE KDLOC_Label_ClearF2119(@TableName VARCHAR(30))
AS 
BEGIN
SET NOCOUNT ON;
DECLARE @SQL_STR VARCHAR(4000)
IF EXISTS(SELECT TAB.NAME FROM SYS.TABLES TAB JOIN SYS.COLUMNS COL ON COL.object_id=TAB.object_id AND COL.NAME='F2119' AND TAB.NAME=@TableName) 
	BEGIN
		SET @SQL_STR='UPDATE ' + @TableName + ' SET F2119=0 WHERE F2119 in (1,3)'
		EXEC(@SQL_STR)
	END
END
GO

if object_id('KDLOC_Label_MOVE2LABELTAB') is not null DROP PROCEDURE KDLOC_Label_MOVE2LABELTAB;
GO

CREATE PROCEDURE KDLOC_Label_MOVE2LABELTAB 
AS 
BEGIN
DECLARE @POS_U_FLDS VARCHAR(2000), @OBJ_U_FLDS VARCHAR(2000), @PRICE_U_FLDS VARCHAR(2000), @ALT_U_FLDS VARCHAR(2000), /*@LABEL_FLDS VARCHAR(2000),*/ @SQLSTR varchar(4000),
		@POS_I_FLDS VARCHAR(2000), @OBJ_I_FLDS VARCHAR(2000), @PRICE_I_FLDS VARCHAR(2000), @ALT_I_FLDS VARCHAR(2000)
/* for update - List of fields from POS_TAB that colide with Label_tab */ 
SELECT @POS_U_FLDS = CASE WHEN ISNULL(@POS_U_FLDS,'')='' THEN COL.NAME+'=POS.'+COL.NAME ELSE @POS_U_FLDS+','+COL.NAME+'=POS.'+COL.NAME END
						FROM SYS.COLUMNS COL
						JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
						WHERE TAB.NAME='POS_TAB'
						AND COL.NAME NOT IN ('F01','F253','F902')
						AND COL.NAME IN (SELECT COL.NAME 
													FROM SYS.COLUMNS COL
													JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
													WHERE TAB.NAME='LABEL_TAB')
						ORDER BY COL.NAME
/* for insert - List of fields from POS_TAB that colide with Label_tab */ 
SELECT @POS_I_FLDS = CASE WHEN ISNULL(@POS_I_FLDS,'')='' THEN 'POS.'+COL.NAME ELSE @POS_I_FLDS+',POS.'+COL.NAME END
						FROM SYS.COLUMNS COL
						JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
						WHERE TAB.NAME='POS_TAB'
						AND COL.NAME NOT IN ('F01','F253','F902')
						AND COL.NAME IN (SELECT COL.NAME 
													FROM SYS.COLUMNS COL
													JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
													WHERE TAB.NAME='LABEL_TAB')
						ORDER BY COL.NAME
/* for update - List of fields from OBJ_TAB that colide with Label_tab */ 
SELECT @OBJ_U_FLDS = CASE WHEN ISNULL(@OBJ_U_FLDS,'')='' THEN COL.NAME+'=OBJ.'+COL.NAME ELSE @OBJ_U_FLDS+','+COL.NAME+'=OBJ.'+COL.NAME END
						FROM SYS.COLUMNS COL
						JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
						WHERE TAB.NAME='OBJ_TAB'
						AND COL.NAME NOT IN ('F253','F902','F21')
						AND COL.NAME IN (SELECT COL.NAME 
													FROM SYS.COLUMNS COL
													JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
													WHERE TAB.NAME='LABEL_TAB')
						ORDER BY COL.NAME
/* for insert - List of fields from OBJ_TAB that colide with Label_tab */ 
SELECT @OBJ_I_FLDS = CASE WHEN ISNULL(@OBJ_I_FLDS,'')='' THEN 'OBJ.'+COL.NAME ELSE @OBJ_I_FLDS+',OBJ.'+COL.NAME END
						FROM SYS.COLUMNS COL
						JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
						WHERE TAB.NAME='OBJ_TAB'
						AND COL.NAME NOT IN ('F253','F902','F21')
						AND COL.NAME IN (SELECT COL.NAME 
													FROM SYS.COLUMNS COL
													JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
													WHERE TAB.NAME='LABEL_TAB')
						ORDER BY COL.NAME
/* for update - List of fields from PRICE_TAB that colide with Label_tab */ 
SELECT @PRICE_U_FLDS = CASE WHEN ISNULL(@PRICE_U_FLDS,'')='' THEN COL.NAME+'=PRI.'+COL.NAME ELSE @PRICE_U_FLDS+','+COL.NAME+'=PRI.'+COL.NAME END
						FROM SYS.COLUMNS COL
						JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
						WHERE TAB.NAME='PRICE_TAB'
						AND COL.NAME NOT IN ('F01','F253','F902')
						AND COL.NAME IN (SELECT COL.NAME 
													FROM SYS.COLUMNS COL
													JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
													WHERE TAB.NAME='LABEL_TAB')
						ORDER BY COL.NAME
/* for insert - List of fields from PRICE_TAB that colide with Label_tab */ 
SELECT @PRICE_I_FLDS = CASE WHEN ISNULL(@PRICE_I_FLDS,'')='' THEN 'PRI.'+COL.NAME ELSE @PRICE_I_FLDS+',PRI.'+COL.NAME END
						FROM SYS.COLUMNS COL
						JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
						WHERE TAB.NAME='PRICE_TAB'
						AND COL.NAME NOT IN ('F01','F253','F902')
						AND COL.NAME IN (SELECT COL.NAME 
													FROM SYS.COLUMNS COL
													JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
													WHERE TAB.NAME='LABEL_TAB')
						ORDER BY COL.NAME
/* for update - List of fields from ALT_TAB that colide with Label_tab */ 
SELECT @ALT_U_FLDS = CASE WHEN ISNULL(@ALT_U_FLDS,'')='' THEN COL.NAME+'=ALT.'+COL.NAME ELSE @ALT_U_FLDS+','+COL.NAME+'=ALT.'+COL.NAME END
						FROM SYS.COLUMNS COL
						JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
						WHERE TAB.NAME='ALT_TAB'
						AND COL.NAME NOT IN ('F01','F126','F253','F902')
						AND COL.NAME IN (SELECT COL.NAME 
													FROM SYS.COLUMNS COL
													JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
													WHERE TAB.NAME='LABEL_TAB')
						ORDER BY COL.NAME
/* for insert - List of fields from ALT_TAB that colide with Label_tab */ 
SELECT @ALT_I_FLDS = CASE WHEN ISNULL(@ALT_I_FLDS,'')='' THEN 'ALT.'+COL.NAME ELSE @ALT_I_FLDS+',ALT.'+COL.NAME END
						FROM SYS.COLUMNS COL
						JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
						WHERE TAB.NAME='ALT_TAB'
						AND COL.NAME NOT IN ('F01','F126','F253','F902')
						AND COL.NAME IN (SELECT COL.NAME 
													FROM SYS.COLUMNS COL
													JOIN SYS.TABLES TAB ON TAB.object_id=COL.object_id
													WHERE TAB.NAME='LABEL_TAB')
						ORDER BY COL.NAME
/*Build update statement */
SET @SQLSTR = 'UPDATE LBL 
	SET '+@POS_U_FLDS+','+@OBJ_U_FLDS+','+@PRICE_U_FLDS+','+@ALT_U_FLDS+ ',F253=GETDATE() , F902=''AUTOLBL'',F95=''Label_Changes.lbz'', F1148=''PAL'' 
		FROM OBJ_TAB OBJ
		LEFT JOIN POS_TAB POS ON OBJ.F01=POS.F01
		LEFT JOIN PRICE_TAB PRI ON OBJ.F01=PRI.F01 AND PRI.F1000=''PAL'' AND PRI.F126=1
		LEFT JOIN ALT_TAB ALT ON ALT.F01=OBJ.F01 AND ALT.F1000=PRI.F1000 AND ISNULL(ALT.F1898,1)=1 
		JOIN LABEL_TAB LBL ON LBL.F1148=''PAL'' AND LBL.F95=''Label_Changes.lbz'' AND LBL.F01=OBJ.F01 AND LBL.F126=1
		WHERE OBJ.F2119=1 OR POS.F2119=1 
'
EXEC(@SQLSTR)
/* build insert Statement */
SET @SQLSTR = 'INSERT INTO LABEL_TAB ('+REPLACE(@POS_I_FLDS,'POS.','')+','+REPLACE(@OBJ_I_FLDS,'OBJ.','')+','+REPLACE(@PRICE_I_FLDS,'PRI.','')+','+REPLACE(@ALT_I_FLDS,'ALT.','')+',F25,F253,F902,F95,F1148,F94)
	SELECT '+@POS_I_FLDS+','+@OBJ_I_FLDS+','+REPLACE(@PRICE_I_FLDS,'PRI.F126','ISNULL(PRI.F126,1)')+','+@ALT_I_FLDS+',F25=NULL, GETDATE() AS F253, ''AUTOLBL'' AS F902, F95=''Label_Changes.lbz'', F1148=''PAL'',F94=1
		FROM OBJ_TAB OBJ
		LEFT JOIN POS_TAB POS ON OBJ.F01=POS.F01
		LEFT JOIN PRICE_TAB PRI ON OBJ.F01=PRI.F01 AND PRI.F1000=''PAL'' AND PRI.F126=1
		LEFT JOIN ALT_TAB ALT ON ALT.F01=OBJ.F01 AND ALT.F1000=PRI.F1000 AND ISNULL(ALT.F1898,1)=1 
		LEFT JOIN LABEL_TAB LBL ON LBL.F1148=''PAL'' AND LBL.F95=''Label_Changes.lbz'' AND LBL.F01=OBJ.F01 AND LBL.F126=1
		WHERE (OBJ.F2119=1 OR POS.F2119=1) AND LBL.F01 IS NULL
'
EXEC(@SQLSTR)
END
GO