/*
 * File: app/view/Tasks/LabelPrint.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Tasks.LabelPrint', {
    extend: 'Ext.form.Panel',
    alias: 'widget.taskslabelprint',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.field.Search',
        'Ext.form.FieldSet',
        'Ext.Label',
        'Ext.field.Checkbox',
        'Ext.field.Select'
    ],

    config: {
        smsToolbar: 'Print',
        smsHost: 'itmhost',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        cls: 'sms-title-close-btn',
                        itemId: 'closeBtn'
                    },
                    {
                        xtype: 'button',
                        cls: 'sms-title-tasks-btn',
                        itemId: 'tasksBtn'
                    },
                    {
                        xtype: 'button',
                        align: 'right',
                        cls: 'sms-title-print-btn',
                        itemId: 'printBtn'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                cls: 'sms-child-tool',
                docked: 'top',
                layout: {
                    type: 'hbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        flex: 1,
                        itemId: 'searchEdit',
                        placeHolder: 'Enter item code'
                    },
                    {
                        xtype: 'button',
                        cls: 'sms-title-scan-btn',
                        docked: 'right',
                        itemId: 'scanCamBtn'
                    }
                ]
            },
            {
                xtype: 'container',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'fieldset',
                        height: 72,
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'container',
                                height: 25,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'sms-displayfield',
                                        width: 150,
                                        clearIcon: false,
                                        name: 'F01',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'label',
                                        flex: 1,
                                        cls: 'sms-label-title',
                                        html: 'Print label'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        smsExec: 'jsSetConfig=TasksLabelInstant,jsValue=',
                                        label: 'Print on scan',
                                        labelAlign: 'right',
                                        labelWidth: 100,
                                        name: 'LabelOnScan'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'container',
                                items: [
                                    {
                                        xtype: 'selectpopup',
                                        smsPop: 'jsPop=list,jsCgi=mFloor_xml_file.xml&files=lbz\\PORTABLE_*.lbz,jsAction=run',
                                        smsExec: 'jsSetConfig=TasksLabelPrint,jsValue=',
                                        width: 300,
                                        label: 'Label',
                                        labelAlign: 'top',
                                        name: 'LabelFormat',
                                        displayField: 'caption',
                                        valueField: 'data'
                                    },
                                    {
                                        xtype: 'selectpopup',
                                        smsPop: 'jsPop=list,jsCgi=mFloor_tasks_label_print_printer.xml,jsAction=run',
                                        smsExec: 'jsSetConfig=TasksLabelPrint,jsValue=',
                                        width: 300,
                                        label: 'Printer',
                                        labelAlign: 'top',
                                        name: 'LabelPrinter',
                                        displayField: 'caption',
                                        valueField: 'data'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Description',
                                labelAlign: 'top',
                                labelWidth: 0,
                                name: 'F02',
                                readOnly: true
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: '',
                        items: [
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'currencyfield',
                                        flex: 0.6,
                                        cls: 'sms-priceamt',
                                        maxWidth: 200,
                                        width: 80,
                                        label: 'Regular',
                                        labelAlign: 'top',
                                        name: 'F30',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        flex: 0.3,
                                        cls: 'sms-priceqty',
                                        maxWidth: 150,
                                        width: 70,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F31',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'currencyfield',
                                        flex: 0.6,
                                        cls: 'sms-priceamt',
                                        maxWidth: 200,
                                        width: 80,
                                        label: 'Tpr',
                                        labelAlign: 'top',
                                        name: 'F181',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        flex: 0.3,
                                        cls: 'sms-priceqty',
                                        maxWidth: 150,
                                        width: 70,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F182',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'currencyfield',
                                        flex: 0.6,
                                        cls: 'sms-priceamt',
                                        maxWidth: 200,
                                        width: 80,
                                        label: 'Sale',
                                        labelAlign: 'top',
                                        name: 'F136',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        flex: 0.3,
                                        cls: 'sms-priceqty',
                                        maxWidth: 150,
                                        width: 70,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F135',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'currencyfield',
                                        flex: 0.6,
                                        cls: 'sms-priceamt',
                                        maxWidth: 200,
                                        width: 80,
                                        label: 'Instore',
                                        labelAlign: 'top',
                                        name: 'F1133',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        flex: 0.3,
                                        cls: 'sms-priceqty',
                                        maxWidth: 150,
                                        width: 70,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F1134',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});