/*
 * File: app/view/Tasks/LabelInstant.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Tasks.LabelInstant', {
    extend: 'Ext.form.Panel',
    alias: 'widget.taskslabelinstant',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.field.Search',
        'Ext.form.FieldSet',
        'Ext.Label',
        'Ext.field.Select',
        'Ext.field.Hidden',
        'Ext.field.Radio'
    ],

    config: {
        smsToolbar: 'Batch',
        smsHost: 'itmhost',
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        cls: 'sms-title-close-btn',
                        itemId: 'closeBtn'
                    },
                    {
                        xtype: 'button',
                        cls: 'sms-title-tasks-btn',
                        itemId: 'tasksBtn'
                    },
                    {
                        xtype: 'button',
                        smsExec: 'jsWin=itminfo',
                        align: 'right',
                        cls: 'sms-title-verify-btn',
                        itemId: 'verifyBtn'
                    },
                    {
                        xtype: 'button',
                        align: 'right',
                        cls: 'sms-title-print-btn',
                        itemId: 'printBtn'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                cls: 'sms-child-tool',
                docked: 'top',
                layout: {
                    type: 'hbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        flex: 1,
                        itemId: 'searchEdit',
                        placeHolder: 'Enter item code'
                    }
                ]
            },
            {
                xtype: 'container',
                layout: 'vbox',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'fieldset',
                        height: 72,
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'container',
                                height: 25,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'sms-displayfield',
                                        width: 150,
                                        clearIcon: false,
                                        name: 'F01',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'label',
                                        flex: 1,
                                        cls: 'sms-label-title',
                                        html: 'Batch label'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        smsExec: 'jsSetConfig=TasksLabelInstant,jsValue=',
                                        label: 'Add on scan',
                                        labelAlign: 'right',
                                        labelWidth: 100,
                                        name: 'LabelOnScan'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'selectpopup',
                                smsPop: 'jsPop=list,jsCgi=mFloor_xml_file.xml&files=lbz\\*.lbz,jsAction=run',
                                smsExec: 'jsSetConfig=TasksLabelInstant,jsValue=',
                                width: 300,
                                label: 'Label template',
                                labelAlign: 'top',
                                name: 'LabelFormat',
                                required: true,
                                displayField: 'caption',
                                valueField: 'data'
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        smsExec: 'jsSetConfig=TasksLabelInstant,jsValue=',
                                        width: 78,
                                        clearIcon: false,
                                        label: 'Label qty',
                                        labelAlign: 'top',
                                        name: 'LabelQuantity',
                                        readOnly: false
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        name: 'LabelDescField'
                                    },
                                    {
                                        xtype: 'textfield',
                                        width: 73,
                                        label: 'Added',
                                        labelAlign: 'top',
                                        name: 'LABEL_TAB-F113',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'hiddenfield',
                                name: 'LabelPrinter'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Description',
                                labelAlign: 'top',
                                name: 'F02',
                                readOnly: true
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        flex: 1,
                        layout: 'vbox',
                        title: '',
                        items: [
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        smsExec: 'jsSetConfig=TasksLabelInstant,jsValue=',
                                        flex: 0.2,
                                        maxWidth: 70,
                                        padding: '13 0 0 0',
                                        name: 'LabelPriceType',
                                        value: 'REG',
                                        checked: true
                                    },
                                    {
                                        xtype: 'currencyfield',
                                        flex: 0.5,
                                        cls: 'sms-priceamt',
                                        maxWidth: 225,
                                        label: 'Regular Price',
                                        labelAlign: 'top',
                                        name: 'F30',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        flex: 0.3,
                                        cls: 'sms-priceqty',
                                        maxWidth: 150,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F31',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                hidden: true,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        smsExec: 'jsSetConfig=TasksLabelInstant,jsValue=',
                                        flex: 0.2,
                                        maxWidth: 70,
                                        padding: '13 0 0 0',
                                        name: 'LabelPriceType',
                                        value: 'TPR'
                                    },
                                    {
                                        xtype: 'currencyfield',
                                        flex: 0.3,
                                        cls: 'sms-priceamt',
                                        maxWidth: 225,
                                        label: 'Tpr Price',
                                        labelAlign: 'top',
                                        name: 'F181',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        flex: 0.3,
                                        cls: 'sms-priceqty',
                                        maxWidth: 150,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F182',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                hidden: true,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        smsExec: 'jsSetConfig=TasksLabelInstant,jsValue=',
                                        flex: 0.2,
                                        maxWidth: 70,
                                        padding: '13 0 0 0',
                                        name: 'LabelPriceType',
                                        value: 'SAL'
                                    },
                                    {
                                        xtype: 'currencyfield',
                                        flex: 0.3,
                                        cls: 'sms-priceamt',
                                        maxWidth: 225,
                                        label: 'Sale Price',
                                        labelAlign: 'top',
                                        name: 'F136',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        flex: 0.3,
                                        cls: 'sms-priceqty',
                                        maxWidth: 150,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F135',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                hidden: true,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        smsExec: 'jsSetConfig=TasksLabelInstant,jsValue=',
                                        flex: 0.2,
                                        maxWidth: 70,
                                        padding: '13 0 0 0',
                                        name: 'LabelPriceType',
                                        value: 'INS'
                                    },
                                    {
                                        xtype: 'currencyfield',
                                        flex: 0.3,
                                        cls: 'sms-priceamt',
                                        maxWidth: 225,
                                        label: 'Price',
                                        labelAlign: 'top',
                                        name: 'F1133',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        flex: 0.3,
                                        cls: 'sms-priceqty',
                                        maxWidth: 150,
                                        label: 'Qty',
                                        labelAlign: 'top',
                                        name: 'F1134',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});