@FMT(CMP,@WIZEXIST(LIVEENTRY)=1,"®WIZRPL(ENTRY=@WIZGET(LIVEENTRY))");
@WIZRPL(TrsOverZero=@FMT(CMP,'@FMT(#,@DBHOT(SAL_TTL_FIND,29999,F65,#))>0',1,0));
@WIZRPL(TrsRefundOn=@FMT(CMP,'@DBHOT(HOT_MEM,CLTRETURNMODE)<>0',1,0));

@FMT(CMP,@WIZGET(TrsOverZero)@WIZGET(TrsRefundOn)=10,"®WIZCLR(TrsOverZero)®WIZCLR(TrsRefundOn)®POST(FCT=117,®TOOLS(PARAMTOCOMA))");
@FMT(CMP,@WIZGET(TrsOverZero)@WIZGET(TrsRefundOn)=01,"®WIZCLR(TrsOverZero)®WIZCLR(TrsRefundOn)®POST(FCT=117,®TOOLS(PARAMTOCOMA))");
@FMT(CMP,@WIZGET(TrsOverZero)@WIZGET(TrsRefundOn)=00,"®WIZCLR(TrsOverZero)®WIZCLR(TrsRefundOn)®POST(sqi=Kinney_ReturnOnGiftCard,®TOOLS(PARAMTOCOMA))");
@FMT(CMP,@WIZGET(TrsOverZero)@WIZGET(TrsRefundOn)=11,"®WIZCLR(TrsOverZero)®WIZCLR(TrsRefundOn)®POST(sqi=Kinney_ReturnOnGiftCard,®TOOLS(PARAMTOCOMA))");



