/* EXECUTE TENDER IF NO ITEM FLAGGUED AS CO (CashOnly) */
@DBHOT(SAL_REG_FIND,F1120 LIKE '%CO%',F65,,=TCASHONLY);
@FMT(CMP,@RPTTTL(TCASHONLY,Z#)=,'®EXEC(®WIZGET(TndMacro))®FMT(CHR,26)');

/* IF CASH ONLY ITEM EXISTS SUBSTRACT AMOUNT ALREADY PAID WITH CASH AND DISPLAY ERROR MESSAGE */
@DBHOT(SAL_TTL_FIND,1201,F65,,-TCASHONLY);
@DBHOT(SAL_TTL_FIND,1205,F65,,-TCASHONLY);
@DBHOT(SAL_TTL_FIND,239,F65,,-TCASHONLY);
@DBHOT(SAL_TTL_FIND,203,F65,,TCASHONLY);

@FMT(CMP,@RPTTTL(TCASHONLY,#)>0,"®WIZRPL(DECLINED=®TOOLS(MESSAGEDLG,®RPTTTL(TCASHONLY,$) NEEDS TO BE PAID ®FMT(CHR,13) BY CASH ONLY,,Cancel))");
@FMT(CMP,@WIZGET(DECLINED)=,'®EXEC(®WIZGET(TndMacro))','®FMT(CHR,27)');
