/* Import Kinney clubmilk points */

@WIZRPL(NAME=Import milk club points);
@WIZRPL(FILE_TYPE=IMPORT);
@WIZRPL(DIR_NAME=@RUNLinks\MilkClub\);
@WIZRPL(FILE_NAME=*.*);
@WIZRPL(FILE_TYPE2=ASCII);
@WIZRPL(CHAR_DELIMITER=#124);
@WIZRPL(RECORD_DELIMITER=#10);
@WIZRPL(MAP_FILE=KDLOC_MilkClub_pts_import.SQM);
@WIZRPL(MULTI_FILE=1);
@WIZRPL(SAVE_DIR=@RUNLinks\MilkClub\Backup\);
@WIZRPL(TARGET=941);
@EXEC(XCH=RECV);

/* PURGE BACKUP */
@WIZSET(SAVE_DIR_PURGE=30);
@WIZRPL(STOP=@DATE(@DSDD,DSD-D@WIZGET(SAVE_DIR_PURGE)F));
@WIZRPL(SRC_PATH=@RUNLinks\MilkClub\Backup\*.*);
@EXEC(XCH=DEL);