/* Export only if data ready */
@FMT(CMP,@DBSELECT(SELECT COUNT(*) FROM KINNEY_TRS_ADD WHERE F1001=1)=0,'®FMT(CHR,27)');

@WIZRPL(STYLE=TXT);
@WIZRPL(OUTPUT=DBT\TMP_KDLOC_TRS_EXPORT_@STORE@TER_S@DBHOT(CNCURRENT).TXT);
@EXEC(CGI=KDLOC_trs_export);

/* USE MOVEFILE TO RENAME USING LOWER CASE */
@WIZRPL(SRC_PATH=@WIZGET(OUTPUT));
@WIZRPL(TAR_PATH=@DBHOT(INI,KinneyDrug.INI,TrsExport,ExportDir)work@DIDD@NOW.det);
@EXEC(XCH=MOVEFILE);

@FMT(CMP,@WIZGET(FILE_CREATED)=1,DELETE KINNEY_TRS_ADD WHERE F1001=2)