/* IF REQUEST COMMING FROM SCHEDULER EXPORT EVERYTHING BASED ON F1100 = 0 - ON MANUAL PROCESS EXPORT BASED ON DATE */
@WIZSET(SCH_TASK=1);

/* BEGIN SQL TRANSACTION */
@DBHOT(MSSQL,STARTTRANSACTION);

/* UPDATE OPERATOR VALIDATED FIELD TO BASE QUERY ON IT WHEN TASK IS COMING FROM SCHEDULER */
@FMT(CMP,@WIZGET(SCH_TASK)=1,UPDATE TRS_PAY SET F1100=2 WHERE F1100=0);

@WIZRPL(STYLE=TXT);
@WIZRPL(OUTPUT=@DBHOT(INI,KinneyDrug.INI,MILKCLUB,ExportDir)MILKCLUB.@DATE(@WIZGET(DATE),DADF).TXT);
@EXEC(CGI=KDLOC_MilkClub_pts_export);

/* UPDATE OPERATOR VALIDATED FIELD TO 1 ONCE EXPORT FROM SCHEDULER HAS BEEN PERFORMED */
@FMT(CMP,@WIZGET(SCH_TASK)@WIZGET(FILE_CREATED)=11,UPDATE TRS_PAY SET F1100=999 WHERE F1100=2);

/* END SQL TRANSACTION */
@DBHOT(MSSQL,COMMIT);