@TOOLS(INSTALL_USP,Usp\PAY_CHARGE_USP.SQL);
@TOOLS(INSTALL_USP,Usp\PAY_GIFT_USP.SQL);
@TOOLS(INSTALL_USP,Usp\PAY_POINT_USP.SQL);
@TOOLS(INSTALL_USP,Usp\PAY_SHOPPER_USP.SQL);
@TOOLS(INSTALL_USP,Usp\SKU_CPN_OFR_SUM.SQL);
@TOOLS(INSTALL_USP,Usp\SMS_GLOBALVARIABLES.SQL);
@TOOLS(INSTALL_USP,Usp\KDLOC_LABEL_CREATION.sql);
@TOOLS(INSTALL_USP,Usp\KDLOC_LABEL_WASNOW_CREATION.sql);
